/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi_juragan_beras;

import static java.awt.image.ImageObserver.WIDTH;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASPIREV5471G
 */
public class Pelanggan1 extends javax.swing.JInternalFrame {
Koneksi k = new Koneksi();
ResultSet rs = null;


public void tampilkandata(){    
DefaultTableModel tbpelanggan = new DefaultTableModel();
        tbpelanggan.addColumn("No. Pelanggan");
       tbpelanggan.addColumn("Nama Pelanggan");
        tbpelanggan.addColumn("Nama Toko");
        tbpelanggan.addColumn("Alamat");
        
        
        try {
            rs=k.ambilData("select * from tbl_pelanggan");
            while (rs.next()) {
                tbpelanggan.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
            }
           jTable1.setModel(tbpelanggan);
           jtNoPelanggan.setEnabled(true);
        } catch (Exception e) {
        }
}
    public Pelanggan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNoPelanggan = new javax.swing.JTextField();
        bttnSimpan = new javax.swing.JButton();
        bttnHapus = new javax.swing.JButton();
        bttnEdit = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bttnTampil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("INPUT DATA PELANGGAN");

        jLabel2.setText("No. Pelanggan");

        bttnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/sv.jpg"))); // NOI18N
        bttnSimpan.setText("Simpan");
        bttnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSimpanActionPerformed(evt);
            }
        });

        bttnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/dt.jpg"))); // NOI18N
        bttnHapus.setText("hapus");
        bttnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnHapusActionPerformed(evt);
            }
        });

        bttnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/ed.jpg"))); // NOI18N
        bttnEdit.setText("Edit");
        bttnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEditActionPerformed(evt);
            }
        });

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/cr.jpg"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Pelanggan");

        jLabel4.setText("Nama Toko");

        jLabel5.setText("Alamat");

        bttnTampil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/tm.jpg"))); // NOI18N
        bttnTampil.setText("Tampilkan");
        bttnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnTampilActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Pelanggan", "Nama Pelanggan", "Nama Toko", "Alamat"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtNoPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(bttnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                            .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(bttnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                            .addComponent(bttnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bttnTampil)
                                        .addGap(53, 53, 53)))))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtNoPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnSimpan)
                    .addComponent(bttnHapus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(bttnEdit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnTampil))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnHapusActionPerformed
    int hasil = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin ingin Hapus?", "Yakin?", JOptionPane.YES_NO_OPTION);
        if (hasil == 0) {
        try { 
        int baris=jTable1.getSelectedRow();
        String no=(String)jTable1.getModel().getValueAt(baris, 0);
        
            boolean j=k.simpanData("delete from tbl_pelanggan where No='"+no+"'");
        tampilkandata();
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "KLIK PADA TABLENYA");
        }
        jtNoPelanggan.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jtNoPelanggan.requestFocus();
        tampilkandata();
        }
        else{
            tampilkandata();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_bttnHapusActionPerformed

    private void bttnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEditActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        String nopel=jtNoPelanggan.getText();
        String nm=jTextField2.getText();
        String toko2=jTextField3.getText();
        String al=jTextField4.getText();
        if((nopel.equals(""))||(nm.equals(""))||
                 (toko2.equals(""))||(al.equals("")))
                 
            {
                JOptionPane.showMessageDialog(rootPane, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
                jtNoPelanggan.requestFocus();
            }
        else{
        boolean j=k.simpanData("Update `tbl_pelanggan` SET `No`='"+nopel+"',"+"`Nama Pelanggan`='"+nm+"'," + "`Nama Toko`='"+toko2+"',"+"`Alamat`='"+al+"'"+" Where `No`='"+nopel+"'");
        JOptionPane.showMessageDialog(rootPane, "Berhasil di Update");   
        tampilkandata();
        jtNoPelanggan.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jtNoPelanggan.requestFocus();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_bttnEditActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void bttnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnTampilActionPerformed
    tampilkandata();    // TODO add your handling code here:
    }//GEN-LAST:event_bttnTampilActionPerformed

    private void bttnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSimpanActionPerformed
     
        String nopel=jtNoPelanggan.getText();
        String nm=jTextField2.getText();
        String toko2=jTextField3.getText();
        String al=jTextField4.getText();
        if((nopel.equals(""))||(nm.equals(""))||
                 (toko2.equals(""))||(al.equals("")))
                 
            {
                JOptionPane.showMessageDialog(rootPane, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
                jtNoPelanggan.requestFocus();
            }
        else{
        boolean j = k.simpanData("insert into tbl_pelanggan value('"+nopel+"','"+nm+"','"+toko2+"','"+al+"')");
        
        
        tampilkandata();
        jtNoPelanggan.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jtNoPelanggan.requestFocus();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_bttnSimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    DefaultTableModel dtm= (DefaultTableModel) jTable1.getModel();
    jtNoPelanggan.setText(dtm.getValueAt(jTable1.getSelectedRow(), 0).toString());
    jTextField2.setText(dtm.getValueAt(jTable1.getSelectedRow(), 1).toString());
    jTextField3.setText(dtm.getValueAt(jTable1.getSelectedRow(), 2).toString());
    jTextField4.setText(dtm.getValueAt(jTable1.getSelectedRow(), 3).toString());    // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
    String nopl=jtNoPelanggan.getText();
        DefaultTableModel tbcari = new DefaultTableModel();
        tbcari.addColumn("No. Pelanggan");
       tbcari.addColumn("Nama Pelanggan");
        tbcari.addColumn("Nama Toko");
        tbcari.addColumn("Alamat");
        if(nopl.equals("")){
            JOptionPane.showMessageDialog(rootPane, "NO HARUS DI ISI", "INFORMASI", WIDTH, null);
                jtNoPelanggan.requestFocus();
        }
        else{
         try {
             rs=k.ambilData("Select * from tbl_pelanggan where No='"+nopl+"'");
             
            if (rs.next()) {
               
            jTextField2.setText(rs.getString(2));
            jTextField3.setText(rs.getString(3));
            jTextField4.setText(rs.getString(4));
                tbcari.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
            
                jTable1.setModel(tbcari);
            jtNoPelanggan.setEnabled(false);
           jTextField2.requestFocus();
            }          
           
           else{
                   JOptionPane.showMessageDialog(rootPane, "DATA TIDAK DITEMUKAN ");
                   jtNoPelanggan.requestFocus();
                   }
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Error Pengambilan Data ");
        }
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton bttnEdit;
    private javax.swing.JButton bttnHapus;
    private javax.swing.JButton bttnSimpan;
    private javax.swing.JButton bttnTampil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jtNoPelanggan;
    // End of variables declaration//GEN-END:variables
}
