/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi_juragan_beras;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASPIREV5471G
 */
public class Pemasok1 extends javax.swing.JInternalFrame {
Koneksi k = new Koneksi();
ResultSet rs = null;
    /**
     * Creates new form Pemasok1
     */
    public Pemasok1() {
        initComponents();
        
    }
    public void tampilkandata(){
DefaultTableModel pemasok = new DefaultTableModel();
        pemasok.addColumn("ID Pemasok");
        pemasok.addColumn("Nama Pemasok");
        pemasok.addColumn("Alamat");
        
        
        try {
            rs=k.ambilData("select * from tbl_pemasok");
            while (rs.next()) {
                pemasok.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            }
           tblPemasok.setModel(pemasok);
        jtPemasok.setText("");
        jtNamaPemasok.setText("");
        jtAlamat.setText("");
        jtPemasok.requestFocus();
        jtPemasok.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Table Tidak Ditemukan");
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtPemasok = new javax.swing.JTextField();
        jtNamaPemasok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtAlamat = new javax.swing.JTextField();
        bttnSimpan = new javax.swing.JButton();
        bttnHapus = new javax.swing.JButton();
        bttnCari = new javax.swing.JButton();
        bttnEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bttnTampil = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPemasok = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel2.setText("ID Pemasok               :");

        jLabel3.setText("Nama Pemasok         :");

        jLabel4.setText("Alamat                      :");

        jtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAlamatActionPerformed(evt);
            }
        });

        bttnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/sv.jpg"))); // NOI18N
        bttnSimpan.setText("Simpan");
        bttnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSimpanActionPerformed(evt);
            }
        });

        bttnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/dt.jpg"))); // NOI18N
        bttnHapus.setText("hapus");
        bttnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnHapusActionPerformed(evt);
            }
        });

        bttnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/cr.jpg"))); // NOI18N
        bttnCari.setText("Cari");
        bttnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCariActionPerformed(evt);
            }
        });

        bttnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/ed.jpg"))); // NOI18N
        bttnEdit.setText("Edit");
        bttnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEditActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("INPUT DATA PEMASOK");

        bttnTampil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/tm.jpg"))); // NOI18N
        bttnTampil.setText("Tampilkan");
        bttnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnTampilActionPerformed(evt);
            }
        });

        tblPemasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Pemasok", "Nama Pemasok", "Alamat"
            }
        ));
        tblPemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPemasokMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPemasok);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(bttnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(bttnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(bttnTampil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jtNamaPemasok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtNamaPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnSimpan)
                    .addComponent(bttnHapus)
                    .addComponent(bttnCari)
                    .addComponent(bttnEdit)
                    .addComponent(bttnTampil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAlamatActionPerformed

    private void bttnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnHapusActionPerformed
    int hasil = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin ingin Hapus?", "Yakin?", JOptionPane.YES_NO_OPTION);
        if (hasil == 0) {
        try{
            
        
        int baris=tblPemasok.getSelectedRow();
        String id=(String)tblPemasok.getModel().getValueAt(baris, 0);
        boolean j=k.simpanData("delete from tbl_pemasok where Id='"+id+"'");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "KLIK PADA TABLENYA");
        }
        
        tampilkandata();
        }
        else{
            tampilkandata();
        }
    }//GEN-LAST:event_bttnHapusActionPerformed

    private void bttnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCariActionPerformed
    String id=jtPemasok.getText();
        String nma=jtNamaPemasok.getText();
        DefaultTableModel tbcari = new DefaultTableModel();
        
        tbcari.addColumn("ID Pemasok");
       tbcari.addColumn("Nama Pemasok");
        tbcari.addColumn("Alamat");
        if(id.equals("")){
         JOptionPane.showMessageDialog(rootPane, "ID Harus Di Isi");
        }
        else{
        try {
            rs=k.ambilData("Select * from tbl_Pemasok where Id='"+id+"'");           
            if (rs.next()) {               
             jtNamaPemasok.setText(rs.getString(2));
            jtAlamat.setText(rs.getString(3));
            
                tbcari.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            tblPemasok.setModel(tbcari);
           jtPemasok.setEnabled(false);
           jtNamaPemasok.requestFocus();
            }
            
            else{
               JOptionPane.showMessageDialog(rootPane, "Data Tidak Ada");
               jtPemasok.requestFocus();
            }  
           
           
           
        } catch (Exception e) {
         JOptionPane.showMessageDialog(rootPane, "Terdapat Kesalahan");
        }}
    }//GEN-LAST:event_bttnCariActionPerformed

    private void bttnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEditActionPerformed
    DefaultTableModel dtm = (DefaultTableModel) tblPemasok.getModel();
    String id= jtPemasok.getText();
    String nama=jtNamaPemasok.getText();
    String alamat=jtAlamat.getText();
        if((id.equals(""))|| (nama.equals("")) || (alamat.equals(""))){       
                JOptionPane.showMessageDialog(rootPane, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
                jtPemasok.requestFocus();
            }
        else{
        boolean j=k.simpanData("Update `tbl_pemasok` SET `Id`='"+id+"',"+"`Nama Pemasok`='"+nama+"'," + "`Alamat`='"+alamat+"'"+"Where `Id`='"+id+"'");
        JOptionPane.showMessageDialog(rootPane, "Berhasil di Update");
        tampilkandata();
        }
    }//GEN-LAST:event_bttnEditActionPerformed

    private void bttnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnTampilActionPerformed
    tampilkandata();    // TODO add your handling code here:
    }//GEN-LAST:event_bttnTampilActionPerformed

    private void bttnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSimpanActionPerformed
    String id= jtPemasok.getText();
        String nama= jtNamaPemasok.getText();
        String alamat2= jtAlamat.getText();
       
        if((id.equals(""))||(nama.equals(""))||
                 (alamat2.equals("")))
            {
                JOptionPane.showMessageDialog(rootPane, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
                jtPemasok.requestFocus();
            }
        else{
        boolean j = k.simpanData("insert into tbl_pemasok value('"+id+"','"+nama+"','"+alamat2+"')");
        tampilkandata();
       
        }              // TODO add your handling code here:
    }//GEN-LAST:event_bttnSimpanActionPerformed

    private void tblPemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPemasokMouseClicked
    DefaultTableModel dtm= (DefaultTableModel) tblPemasok.getModel();
    jtPemasok.setText(dtm.getValueAt(tblPemasok.getSelectedRow(), 0).toString());
    jtNamaPemasok.setText(dtm.getValueAt(tblPemasok.getSelectedRow(), 1).toString());
    jtAlamat.setText(dtm.getValueAt(tblPemasok.getSelectedRow(), 2).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPemasokMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCari;
    private javax.swing.JButton bttnEdit;
    private javax.swing.JButton bttnHapus;
    private javax.swing.JButton bttnSimpan;
    private javax.swing.JButton bttnTampil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtAlamat;
    private javax.swing.JTextField jtNamaPemasok;
    private javax.swing.JTextField jtPemasok;
    private javax.swing.JTable tblPemasok;
    // End of variables declaration//GEN-END:variables

}