/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi_juragan_beras;

import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASPIREV5471G
 */
public class Transaksi_Penjualan1 extends javax.swing.JInternalFrame {
Koneksi k = new Koneksi();
ResultSet rs = null;
    
    public void tampilkandata(){
DefaultTableModel tbjual = new DefaultTableModel();
        tbjual.addColumn("No. Transaksi");
        tbjual.addColumn("No. Pelanggan");
        tbjual.addColumn("Nama Toko");
        tbjual.addColumn("Nama Pelanggan");
        tbjual.addColumn("Tanggal Transaksi");
        tbjual.addColumn("Jenis Beras");
        tbjual.addColumn("Jumlah Beli");
        tbjual.addColumn("Harga");
        tbjual.addColumn("Total");
        tbjual.addColumn("Bayar");
        tbjual.addColumn("Kembali");
        
        
        try {
            rs=k.ambilData("select * from tbl_jual");
            
            
            while (rs.next()) {
                tbjual.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)
                ,rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11)});
            }
        jTable1.setModel(tbjual);
        notransaksi.setText("");
        nopelanggan.setText("");
        namatoko.setText("");
        namapelanggan.setText("");
        ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText("");
        jenisbarang.setSelectedItem("Pandan Wangi");
        jumlahbeli.setText("");
        harga.setText("");
        totalharga.setText("");
        bayar2.setText("");
        kembali.setText("");
        
        
        notransaksi.setEnabled(true);
        nopelanggan.setEnabled(true);
        namatoko.setEnabled(true);
        namapelanggan.setEnabled(true);
        notransaksi.requestFocus();
        

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Table Tidak Ditemukan");
        }}
    /**
     * Creates new form Transaksi_Penjualan1
     */
    public Transaksi_Penjualan1() {
        initComponents();
    }
    int total3,bayar;
    void hitung(){
        int hargajual,jumlahbeli2;
        hargajual = Integer.parseInt(harga.getText());
        jumlahbeli2 = Integer.parseInt(jumlahbeli.getText());
        total3=hargajual*jumlahbeli2;
        totalharga.setText(""+total3);
    }
    void kembalian(){
        int kembalian;
        bayar = Integer.parseInt(bayar2.getText());
        kembalian=bayar-total3;
        kembali.setText(""+kembalian);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        notransaksi = new javax.swing.JTextField();
        nopelanggan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namatoko = new javax.swing.JTextField();
        namapelanggan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jenisbarang = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jumlahbeli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalharga = new javax.swing.JTextField();
        bayar2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kembali = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnTampil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        harga = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        btnHitungKembalian = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("TRANSAKSI PENJUALAN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("No.Transaksi");

        notransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notransaksiActionPerformed(evt);
            }
        });

        nopelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nopelangganKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("No. Pelanggan");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Nama Toko");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Nama Pelanggan");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal Transaksi");

        jenisbarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pandan Wangi", "Rojolele", "Manggis", "ABC" }));
        jenisbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisbarangActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Jenis Beras");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Jumlah Beli");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Total");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Bayar");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Kembali");

        btnCari.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/cr.jpg"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/ed.jpg"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/dt.jpg"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/sv.jpg"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTampil.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnTampil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/tm.jpg"))); // NOI18N
        btnTampil.setText("Tampilan");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Transaksi", "No. Pelanggan", "Nama Toko", "Nama Pelanggan", "Tanggal Transaksi", "Jenis Beras", "Jumlah Beli", "Total", "Bayar", "Kembali"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel12.setText("Harga");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnHitungKembalian.setText("Hitung Kembalian");
        btnHitungKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungKembalianActionPerformed(evt);
            }
        });

        jButton8.setText("Klik NO Pel");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jenisbarang, 0, 230, Short.MAX_VALUE)
                            .addComponent(namatoko)
                            .addComponent(namapelanggan)
                            .addComponent(jumlahbeli)
                            .addComponent(nopelanggan)
                            .addComponent(harga)
                            .addComponent(notransaksi)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalharga)
                                    .addComponent(bayar2)
                                    .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(btnTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnHitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnHitungKembalian))))))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(notransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nopelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(namatoko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(namapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCari)
                            .addComponent(btnEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTampil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHitung)
                            .addComponent(btnHitungKembalian))))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(totalharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(bayar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
     String notr=notransaksi.getText();
        DefaultTableModel tbcari = new DefaultTableModel();
         tbcari.addColumn("No. Transaksi");
        tbcari.addColumn("No. Pelanggan");
        tbcari.addColumn("Nama Toko");
        tbcari.addColumn("Nama Pelanggan");
        tbcari.addColumn("Tanggal Transaksi");
        tbcari.addColumn("Jenis Beras");
        tbcari.addColumn("Jumlah Beli");
        tbcari.addColumn("Harga");
        tbcari.addColumn("Total");
        tbcari.addColumn("Bayar");
        tbcari.addColumn("Kembali");
        if(notr.equals("")){
            JOptionPane.showMessageDialog(rootPane, "NO TRANSAKSI HARUS DI ISI", "INFORMASI", WIDTH, null);
                notransaksi.requestFocus();
        }
        else{
         try {
             rs=k.ambilData("Select * from tbl_jual where No ='"+notr+"'");
             
            if (rs.next()) {
               
        nopelanggan.setText(rs.getString(2));
        namatoko.setText(rs.getString(3));
        namapelanggan.setText(rs.getString(4));
        ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(rs.getString(5));
        jenisbarang.setSelectedItem(rs.getString(6));
        jumlahbeli.setText(rs.getString(7));
        harga.setText(rs.getString(8));
        totalharga.setText(rs.getString(9));
        bayar2.setText(rs.getString(10));
        kembali.setText(rs.getString(11));
        
        tbcari.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)
        ,rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11)});
            
                jTable1.setModel(tbcari);
            notransaksi.setEnabled(false);
            nopelanggan.setEnabled(false);
            namatoko.setEnabled(false);
            namapelanggan.setEnabled(false);
            jDateChooser1.requestFocus();
           
            }          
           
           else{
                   JOptionPane.showMessageDialog(rootPane, "DATA TIDAK DITEMUKAN ");
                   notransaksi.requestFocus();
                   }
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Error Pengambilan Data ");
        }
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    Koneksi k = new Koneksi();
    String notrans2 = notransaksi.getText();
    String nopelanggan2 = nopelanggan.getText();
    String namatoko2 =  namatoko.getText();
    String namapelanggan2 = namapelanggan.getText();
    String tgltransaksi2 = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
    String jenis = jenisbarang.getSelectedItem().toString();
    String jumlahbeli2 = jumlahbeli.getText();
    String harga2 = harga.getText();
    String total = totalharga.getText();
    String bayar = bayar2.getText();
    String kembali2 = kembali.getText();
    
    boolean j = k.simpanData("insert into tbl_jual value('"+notrans2+"','"+nopelanggan2+"','"+namatoko2+"','"+namapelanggan2+"','"+tgltransaksi2+"'"
            + ",'"+jenis+"','"+jumlahbeli2+"','"+harga2+"','"+total+"','"+bayar+"','"+kembali2+"')");
        tampilkandata();
    
// TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void notransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notransaksiActionPerformed

    private void jenisbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisbarangActionPerformed
    String h = jenisbarang.getSelectedItem().toString();
        if("Pandan Wangi".equals(h)){
            harga.setText("250000");
            
        }
        else if("Rojolele".equals(h)){
            harga.setText("225500");
            
        }
        else if("Manggis".equals(h)){
            harga.setText("212000");
        }
        else {
            harga.setText("200000");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jenisbarangActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        hitung();    // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnHitungKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungKembalianActionPerformed
    kembalian();    // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungKembalianActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String nopl=nopelanggan.getText();
        DefaultTableModel tbjual = new DefaultTableModel();
       
        tbjual.addColumn("No. Pelanggan");
        tbjual.addColumn("Nama Toko");
        tbjual.addColumn("Nama Pelanggan");
        
        if(nopl.equals("")){
            JOptionPane.showMessageDialog(rootPane, "NO PELANGGAN HARUS DI ISI", "INFORMASI", WIDTH, null);
                nopelanggan.requestFocus();
        }
        else{
         try {
            rs=k.ambilData("Select * from tbl_pelanggan where No='"+nopl+"'");
             
            if (rs.next()) {
        
        namatoko.setText(rs.getString(3));
        namapelanggan.setText(rs.getString(2));
        nopelanggan.setEnabled(false);
        namatoko.setEnabled(false);
        namapelanggan.setEnabled(false);
        jDateChooser1.requestFocus();
            }          
            else{
                JOptionPane.showMessageDialog(rootPane, "Data Tidak Ditemukan");
                nopelanggan.requestFocus();
            }
           } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Error Pengambilan Data ");
        }
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
    tampilkandata();    // TODO add your handling code here:
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    int hasil = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin ingin Hapus?", "Yakin?", JOptionPane.YES_NO_OPTION);
    if(hasil==0){
        try {
            int baris=jTable1.getSelectedRow();
            String no = (String) jTable1.getModel().getValueAt(baris, 0);
            boolean j = k.simpanData("Delete from tbl_jual where No = '"+no+"'");
            tampilkandata();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "KLIK PADA TABELNYA");
        }
    }else{
        tampilkandata();
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
    notransaksi.setText(dtm.getValueAt(jTable1.getSelectedRow(), 0).toString());
    nopelanggan.setText(dtm.getValueAt(jTable1.getSelectedRow(), 1).toString());
    namatoko.setText(dtm.getValueAt(jTable1.getSelectedRow(), 2).toString());
    namapelanggan.setText(dtm.getValueAt(jTable1.getSelectedRow(), 3).toString());
    ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(dtm.getValueAt(jTable1.getSelectedRow(), 4).toString());
    jenisbarang.setSelectedItem(dtm.getValueAt(jTable1.getSelectedRow(), 5).toString());
    jumlahbeli.setText(dtm.getValueAt(jTable1.getSelectedRow(), 6).toString());
    harga.setText(dtm.getValueAt(jTable1.getSelectedRow(), 7).toString());
    totalharga.setText(dtm.getValueAt(jTable1.getSelectedRow(), 8).toString());
    bayar2.setText(dtm.getValueAt(jTable1.getSelectedRow(), 9).toString());
    kembali.setText(dtm.getValueAt(jTable1.getSelectedRow(), 10).toString());
    
    
    }//GEN-LAST:event_jTable1MouseClicked

    private void nopelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nopelangganKeyPressed
    
    }//GEN-LAST:event_nopelangganKeyPressed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        String no=notransaksi.getText();
        String nopel=nopelanggan.getText();
        String namatok=namatoko.getText();
        String namapel=namapelanggan.getText();
        String tgltran=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String jnis=jenisbarang.getSelectedItem().toString();
        String jumlahbel=jumlahbeli.getText();
        String hrg=harga.getText();
        String tot=totalharga.getText();
        String bayar=bayar2.getText();
        String kmbl=kembali.getText();
        
        if((no.equals(""))||(nopel.equals(""))||(namatok.equals(""))||(namapel.equals(""))
                ||(tgltran.equals(""))||(jnis.equals(""))||(jumlahbel.equals(""))
                ||(hrg.equals(""))||(tot.equals(""))
                ||(bayar.equals(""))||(kmbl.equals(""))){
                JOptionPane.showMessageDialog(rootPane, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
                notransaksi.requestFocus();
                
            }
            else {
         boolean j=k.simpanData("UPDATE `tbl_jual` SET `No` ='"+no+"'," +
                                "`No. Pelanggan` = '"+nopel+"'," +
                                "`Nama Toko` = '"+namatok+"'," +
                                "`Nama Pelanggan` = '"+namapel+"'," +
                                "`Tanggal Transaksi` = '"+tgltran+"'," +
                                "`Jenis Beras` = '"+jnis+"'," +
                                "`Jumlah Beli` = '"+jumlahbel+"'," +
                                "`Harga` = '"+hrg+"'," +
                                "`Total` = '"+tot+"'," +
                                "`Bayar` = '"+bayar+"'," +
                                "`Kembali` = '"+kmbl+"'" +
                                "WHERE `No` = '"+no+"'" +
                                "AND `No. Pelanggan` = '"+nopel+"'");
        JOptionPane.showMessageDialog(rootPane, "Berhasil di Update");     
        tampilkandata();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar2;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnHitungKembalian;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTampil;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton8;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jenisbarang;
    private javax.swing.JTextField jumlahbeli;
    private javax.swing.JTextField kembali;
    private javax.swing.JTextField namapelanggan;
    private javax.swing.JTextField namatoko;
    private javax.swing.JTextField nopelanggan;
    private javax.swing.JTextField notransaksi;
    private javax.swing.JTextField totalharga;
    // End of variables declaration//GEN-END:variables
}
